// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwlvlnfiuuiflfahnlhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bHZsbmZpdXVpZmxmYWhubGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzYyMDYsImV4cCI6MjA3MTI1MjIwNn0.u-g_LTwcx8InBt89Qe2vPgyCb0fkK7N23UlNsIGpqoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});